version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
